name: CI
on:
  push:
    branches: [ main, development, CICD-GitubActions ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build web-server
        working-directory: ./src/webserver
        run: |
          build_number=${{github.run_number}}
          sudo docker build -t webserver .
          sudo docker tag webserver $build_number
          sudo docker images


