name: Front-End CI/CD
on:
  push:
    branches:
      - main
      - development
    paths:
      - src/front-end/**
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        working-directory: ./src/front-end/home-led-controller
        run: npm ci
      - name: Build front-end
        working-directory: ./src/front-end/home-led-controller
        run: |
          set -x

          case "${{ github.ref }}" in
            refs/heads/development) target_tag="development" ;;
            refs/heads/main) target_tag="production" ;;
            *)
              echo "unknown target ref: ${{ github.ref }}"
              exit 1
          esac

          if [ $target_tag = development ]
          then
            npm run build:development
          else
            npm run build:production
          fi

          aws --region $AWS_REGION s3 sync build/ s3://home-led-controller/$target_tag/
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
