name: RESTAPI CI/CD
on:
  push:
    branches:
      - main
      - development
    paths:
      - src/webserver/**
  workflow_dispatch:
jobs:
  update-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Upload config files
        run: |
          sed -i "s/<<AWSACCOUNT>>/${AWS_ACCOUNT_ID}/g" ./src/webserver/start.sh
          sed -i "s/<<AWSREGION>>/${AWS_REGION}/g" ./src/webserver/start.sh

          aws s3 cp ./src/webserver/start.sh s3://home-led-controller/config/
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker for linux/arm/v7 (Raspberry Pi) builds
        run: |
          docker run --privileged --rm tonistiigi/binfmt --install all

      - name: Build web-server
        working-directory: ./src/webserver
        run: |
          set -x

          case "${{ github.ref }}" in
            refs/heads/development) target_tag="development" ;;
            refs/heads/main) target_tag="production" ;;
            *)
              echo "unknown target ref: ${{ github.ref }}"
              exit 1
          esac

          build_number=${{github.run_number}}
          commit_hash=${{ github.sha }}
          PRIMARY_TAG=$target_tag
          SECONDARY_TAG="${target_tag}-${build_number}-${commit_hash}"

          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
          sudo docker buildx build --platform linux/arm/v7 -t webserver .
          docker tag webserver:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/home-led-controller:$PRIMARY_TAG
          docker tag webserver:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/home-led-controller:$SECONDARY_TAG
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/home-led-controller:$PRIMARY_TAG
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/home-led-controller:$SECONDARY_TAG
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
